"""
generate_bookings.py — synthetic booking simulator     PLACEHOLDER: S.3 Wave B

STATUS
Not implemented. This file exists in Wave A so the filename, the CLI contract and
the design are fixed before the code is written; golden rule 1 in doc/claude.md is
"implement ONLY the wave pasted in the prompt", and the simulator is Wave B's
substance. Running it now exits with a message pointing here.

────────────────────────────────────────────────────────────────────────────────
WHY SYNTHETIC DATA IS THE HONEST CHOICE HERE, NOT A SHORTCUT
────────────────────────────────────────────────────────────────────────────────
Measured against the live Supabase database on 2026-08-24:

    bookings                                   22 rows
      confirmed 12 · no_show 6 · cancelled 3 · rejected 1
    slots WHERE status = 'booked'                0 rows
    slots                                    3,825 rows
    venues                                      10  (2 cities, 2 sports)
    SELECT count(DISTINCT price) FROM slots
      GROUP BY venue_id                          1  for EVERY venue

The last line is the one that decides this. Every slot at a venue is priced at that
venue's `price_per_hour`. There is not one observation anywhere in the data of the
same slot offered at two different prices — so the data contains NO PRICE
ELASTICITY SIGNAL AT ALL. This is not a matter of having too few rows; it is a
structural absence. No model, of any sophistication, can learn how demand responds
to price from data in which price never varied.

Since the milestone's deliverable is a dynamic PRICE suggestion, the price response
has to come from somewhere. There are two options and only one of them is honest:

  (a) Train on 22 rows with no price variation and present the output as a learned
      market model. That is a fabricated result.
  (b) Write down the demand assumptions explicitly, in code, with citations to
      where each number came from; generate data from them; train a real model; and
      state plainly that the model recovers the simulator's structure.

(b) is what this file does. The honest claim, which reports/model_card.md must make
in these words, is:

    "Trained on synthetic data generated by training/generate_bookings.py with a
     fixed seed. The model demonstrably recovers the demand structure the simulator
     encodes and generalises across hour, day-of-week, lead time and venue tier. It
     has NOT learned real Pakistani market demand — the production database
     contains 22 bookings and no price variation, so no such model can yet be
     trained. Retraining on real bookings is planned once the platform has
     accumulated them; the training script is unchanged by that switch, only the
     input CSV."

That paragraph is worth more to an FYP committee than a fake ROC-AUC, and it is the
difference between a defensible engineering decision and a claim that collapses on
the first question.

────────────────────────────────────────────────────────────────────────────────
WHAT THE SIMULATOR MUST DO (Wave B)
────────────────────────────────────────────────────────────────────────────────
Model the LATENT DEMAND for each slot, then decide booked/not-booked from it. The
schema-mirroring part matters: the generated CSV must have the columns
core/features.py consumes, so training reads it through the SAME build_frame() the
service uses at serve time.

  1. INVENTORY. Walk a date range x venues x operating hours, one row per slot,
     mirroring how backend/src/routes/owner.js's slot generator lays out real
     inventory. Draw venue attributes (sport, city, price_per_hour, rating) from
     the real distribution measured above — 2 cities, 2 sports, PKR 1,500–4,000 —
     so the feature ranges the model sees match the ranges it will be served.

  2. LATENT DEMAND, multiplicative, each factor an explicit stated assumption with
     its reasoning in a comment:

       base                 sport/city baseline occupancy
       x hour_factor        evening peak (18–22 PKT); dead mornings
       x dow_factor         Fri/Sat/Sun above weekday
       x lead_factor        bookings cluster 0–3 days out, thin beyond ~14
       x season_factor      monsoon (Jul–Aug) suppresses outdoor play; Dec–Feb good
       x rating_factor      higher-rated venues fill better; NaN → neutral
       x price_factor       ELASTICITY — the whole point (see 3)

  3. PRICE ELASTICITY. `price_factor = price_ratio ** (-elasticity)`, with
     `price_ratio` sampled across [PRICE_RATIO_MIN, PRICE_RATIO_MAX] = 0.70–1.50
     from core/features.py, so the training band and the serve-time sweep band are
     the same constant and a suggestion can never be an extrapolation.

     Elasticity must be HIGHER off-peak than on-peak — a Tuesday 11am player will
     shop on price; a Friday 8pm team wants that specific slot. That asymmetry is
     the interesting thing for the model to learn and the reason the suggestion
     differs by slot instead of being a flat percentage. It also produces the
     behaviour an owner can sanity-check: raise peak prices, discount off-peak.

  4. REALISM WITHOUT CHEATING. Bernoulli draw on the clipped latent probability, so
     the label is stochastic and the model cannot reach ROC-AUC 1.0 by inverting
     the generator. A perfect score on synthetic data is evidence of a leak, not of
     a good model, and a committee that has seen one before will ask.

  5. REPRODUCIBILITY. `--seed` (default fixed), and the seed plus every parameter
     written into data/bookings_meta.json next to the CSV. The claim "this model is
     reproducible" has to be checkable by re-running one command.

CLI CONTRACT (fixed now, implemented in Wave B)
    python training/generate_bookings.py [--rows 40000] [--seed 42]
                                         [--out data/bookings_synth.csv]
                                         [--start 2026-01-01] [--days 240]

OUTPUT
    data/bookings_synth.csv     one row per offered slot + the `booked` label
    data/bookings_meta.json     seed, parameters, row count, generated_at

WHAT IT MUST NOT DO
  * Not touch the database. Read-only would still be a Postgres dependency in a
    training pipeline, and the venue distribution it needs is four numbers recorded
    above in a comment.
  * Not import anything under app/routers/. Training must not depend on the web
    layer; the ONLY shared code is app/core/features.py, and that direction of
    dependency is deliberate.
"""

from __future__ import annotations

import sys

MESSAGE = """
training/generate_bookings.py is not implemented yet.

  It is scheduled for S.3 Wave B. This file currently holds the simulator design
  (read the module docstring — it explains why the training data must be synthetic
  and exactly what the generator has to encode).

  Wave A shipped: app/core/features.py (the frozen feature contract), the FastAPI
  service, and backend/src/services/mlClient.js with its heuristic fallback.
"""


def main() -> None:
    raise SystemExit(MESSAGE)


if __name__ == "__main__":
    main()
    sys.exit(0)  # pragma: no cover - unreachable
